name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Prepare Deployment Structure
        run: |
          # 创建部署目录
          mkdir -p deploy-temp
          
          # 复制主项目文件到根目录
          cp -r public/* deploy-temp/ || true
          cp index.html deploy-temp/ || true
          cp -r jsx deploy-temp/ || true
          cp -r lib deploy-temp/ || true
          cp -r CSXS deploy-temp/ || true
          
          # 直接复制docs目录到doc子目录（不构建VitePress）
          mkdir -p deploy-temp/doc
          cp -r docs/* deploy-temp/doc/
          
          # 创建.nojekyll文件
          touch deploy-temp/.nojekyll
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: deploy-temp
          branch: gh-pages
          clean: true
          single-commit: true