name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Prepare Deployment Structure
        run: |
          # 创建部署目录
          mkdir -p deploy-temp
          
          # 复制主项目文件到根目录
          if [ -d "public" ]; then cp -r public/* deploy-temp/ 2>/dev/null || true; fi
          if [ -f "index.html" ]; then cp index.html deploy-temp/; fi
          if [ -d "jsx" ]; then cp -r jsx deploy-temp/; fi
          if [ -d "lib" ]; then cp -r lib deploy-temp/; fi
          if [ -d "CSXS" ]; then cp -r CSXS deploy-temp/; fi
          
          # 直接复制docs目录到doc子目录（不构建VitePress）
          mkdir -p deploy-temp/doc
          if [ -d "docs" ]; then cp -r docs/* deploy-temp/doc/ 2>/dev/null || true; fi
          
          # 创建.nojekyll文件
          touch deploy-temp/.nojekyll
          
          # 验证部署目录内容
          echo "Deploy directory contents:"
          ls -la deploy-temp/
          if [ -d "deploy-temp/doc" ]; then
            echo "Doc directory contents:"
            ls -la deploy-temp/doc/
          fi
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: deploy-temp
          branch: gh-pages
          clean: true
          single-commit: true
          token: ${{ secrets.GITHUB_TOKEN }}